<?php

namespace App\Services;

use CodeIgniter\Database\BaseConnection;

/**
 * Spreadsheet Gangguan Transactional Import Service (CR-01 Phase 2)
 *
 * Responsibilities:
 * - Governed transactional execution for committing an approved Import Plan.
 * - Enforces Confirmation Barrier (requires confirm === true and matching confirmation_token).
 * - Full ACID transaction boundary with automatic rollback on error.
 * - Idempotency guard via source_record_hash check.
 * - Zero mutation on unrelated tables (Assets, Temuan, Penyulang, Sections, etc.).
 */
class SpreadsheetGangguanImportService
{
    protected BaseConnection $db;
    protected CauseCodeResolutionService $causeResolver;

    public function __construct(
        ?BaseConnection $db = null,
        ?CauseCodeResolutionService $causeResolver = null
    ) {
        $this->db            = $db ?? \Config\Database::connect();
        $this->causeResolver = $causeResolver ?? new CauseCodeResolutionService($this->db);
    }

    /**
     * Commit an approved Import Plan to historical_feeder_interruptions within an ACID transaction.
     *
     * @param array $importPlan The validated Import Plan generated by SpreadsheetGangguanImportPlanService
     * @param string $confirmationToken Confirmation token from the plan
     * @param bool $confirm Explicit confirmation flag (MUST be true)
     * @return array Commit result and execution metadata
     */
    public function commitImportPlan(array $importPlan, string $confirmationToken, bool $confirm = false): array
    {
        // 1. Strict Confirmation Barrier
        if ($confirm !== true) {
            return [
                'success' => false,
                'status'  => 'CONFIRMATION_REJECTED',
                'error'   => 'Operasi commit ditolak: Konfirmasi eksplisit (confirm: true) diperlukan untuk menulis ke database.',
                'inserted_count' => 0,
            ];
        }

        $planId = $importPlan['import_plan_id'] ?? null;
        $expectedToken = $importPlan['confirmation_token'] ?? null;

        if (!$planId || !$expectedToken || $confirmationToken !== $expectedToken) {
            return [
                'success' => false,
                'status'  => 'INVALID_CONFIRMATION_TOKEN',
                'error'   => 'Operasi commit ditolak: Token konfirmasi tidak cocok atau Import Plan tidak valid.',
                'inserted_count' => 0,
            ];
        }

        $plannedRows = $importPlan['planned_rows'] ?? [];
        if (empty($plannedRows)) {
            return [
                'success' => false,
                'status'  => 'EMPTY_IMPORT_PLAN',
                'error'   => 'Import Plan tidak memiliki baris data untuk diproses.',
                'inserted_count' => 0,
            ];
        }

        // 2. Begin ACID Transaction
        $this->db->transBegin();

        try {
            $batchCode    = 'BATCH-GDR-' . date('Ymd-His');
            $sourceFile   = $importPlan['source']['filename'] ?? 'unknown_source.xlsx';
            $sheetTitle   = $importPlan['source']['sheet_name'] ?? 'DEFAULT';

            $insertedCount = 0;
            $skippedDupes  = 0;
            $heldCount     = 0;
            $insertedIds   = [];

            foreach ($plannedRows as $item) {
                $disposition = $item['disposition'] ?? 'INVALID';
                $row         = $item['source_data'] ?? [];
                $feederRes   = $item['feeder_resolution'] ?? [];

                if ($disposition !== 'READY_FOR_IMPORT') {
                    if (str_contains($disposition, 'SKIP')) {
                        $skippedDupes++;
                    } else {
                        $heldCount++;
                    }
                    continue;
                }

                $recordHash = $row['_raw_hash'] ?? hash('sha256', json_encode($row));

                // Idempotency Check in Database
                $existing = $this->db->table('historical_feeder_interruptions')
                    ->where('source_record_hash', $recordHash)
                    ->countAllResults();

                if ($existing > 0) {
                    $skippedDupes++;
                    continue;
                }

                // Resolve Cause Code
                $rawCause = $row['cause_raw'] ?? null;
                $causeRes = $this->causeResolver->resolveCause($rawCause);

                $insertData = [
                    'batch_id'                => $batchCode,
                    'source_system'           => 'SPREADSHEET_CONTROLLED_IMPORT',
                    'source_sheet_name'       => $sheetTitle,
                    'source_row_number'       => (int)($row['_source_row_number'] ?? 0),
                    'source_record_hash'      => $recordHash,
                    'raw_payload_json'        => json_encode($row, JSON_UNESCAPED_UNICODE),
                    'event_date'              => $row['event_date'] ?? date('Y-m-d'),
                    'interruption_started_at' => $row['interruption_started_at'] ?? null,
                    'interruption_ended_at'   => $row['interruption_ended_at'] ?? null,
                    'outage_duration_minutes' => (float)($row['outage_duration_minutes'] ?? 0),
                    'substation_name'         => $row['substation_name'] ?? 'UNKNOWN_GI',
                    'ulp_name'                => $row['ulp_name'] ?? 'UNKNOWN_ULP',
                    'feeder_name'             => $feederRes['resolved_penyulang_name'] ?? $row['feeder_name'],
                    'switching_device_type'   => $row['switching_device_type'] ?? 'PMT',
                    'device_name'             => $row['device_name'] ?? '',
                    'relay_trip_type'         => $row['relay_trip_type'] ?? 'DGR',
                    'faulted_phase'           => $row['faulted_phase'] ?? '',
                    'weather_condition'       => $row['weather_condition'] ?? 'cerah',
                    'fault_current_amperes'   => (float)($row['fault_current_amperes'] ?? 0),
                    'energy_not_supplied_kwh' => (float)($row['energy_not_supplied_kwh'] ?? 0),
                    'interruption_category'   => $row['interruption_category'] ?? 'PERMANENT',
                    'interruption_group'      => $row['interruption_group'] ?? 'GGN_PENYULANG',
                    'field_narrative_raw'     => $row['field_narrative_raw'] ?? '',
                    'restoration_action_raw'  => $row['restoration_action_raw'] ?? '',
                    'cause_raw'               => $causeRes['cause_raw'],
                    'cause_canonical_code'    => $causeRes['cause_canonical_code'],
                    'cause_category'          => $causeRes['cause_category'],
                    'cause_mapping_status'    => $causeRes['cause_mapping_status'],
                    'extracted_zone_section'  => $row['extracted_zone_section'] ?? null,
                    'extracted_distance_kms'  => $row['extracted_distance_kms'] ?? null,
                    'asset_reference_raw'     => $row['asset_reference_raw'] ?? null,
                    'created_at'              => date('Y-m-d H:i:s'),
                ];

                $this->db->table('historical_feeder_interruptions')->insert($insertData);
                $insertedId = $this->db->insertID();
                $insertedIds[] = $insertedId;
                $insertedCount++;
            }

            // Commit Transaction
            $this->db->transCommit();

            return [
                'success'           => true,
                'status'            => 'COMMITTED',
                'batch_id'          => $batchCode,
                'import_plan_id'    => $planId,
                'inserted_count'    => $insertedCount,
                'skipped_duplicates'=> $skippedDupes,
                'held_count'        => $heldCount,
                'inserted_ids'      => $insertedIds,
                'committed_at'      => date('Y-m-d H:i:s'),
            ];
        } catch (\Throwable $e) {
            // Automatic Rollback on any failure
            $this->db->transRollback();

            return [
                'success'        => false,
                'status'         => 'TRANSACTION_ROLLED_BACK',
                'error'          => 'Terjadi kegagalan saat import. Transaksi di-rollback penuh: ' . $e->getMessage(),
                'inserted_count' => 0,
            ];
        }
    }
}
