<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class RollbackSyntheticAssetsAndEnforceFeederScope extends Migration
{
    public function up()
    {
        $db = \Config\Database::connect();

        // 1. Unlink temuan records from synthetic assets
        if ($db->tableExists('temuan')) {
            $db->table('temuan')
                ->where('asset_id >', 3)
                ->update(['asset_id' => null]);
        }

        // 2. Remove synthetic asset relationships created from field findings ingestion
        if ($db->tableExists('asset_relationships')) {
            $db->table('asset_relationships')
                ->where('source', 'FIELD_FINDING_INGESTION')
                ->delete();
        }

        // 3. Remove synthetic assets generated by migration 000018, preserving only original baseline assets (ID 1, 2, 3)
        if ($db->tableExists('assets')) {
            $db->table('assets')
                ->where('id >', 3)
                ->delete();
        }

        // 4. Ensure standard construction_types exist for asset classification
        if ($db->tableExists('construction_types')) {
            $ctCount = $db->table('construction_types')->countAllResults();
            if ($ctCount === 0) {
                $constructions = [
                    ['code' => 'TM-1', 'name' => 'TM-1 Tiang Tumpu', 'asset_category' => 'TIANG', 'network_type' => 'JTM', 'description' => 'Tiang penumpu lurus SUTM 20kV'],
                    ['code' => 'TM-2', 'name' => 'TM-2 Tiang Sudut Kecil', 'asset_category' => 'TIANG', 'network_type' => 'JTM', 'description' => 'Tiang sudut deviasi kecil (0-15 derajat)'],
                    ['code' => 'TM-3', 'name' => 'TM-3 Tiang Sudut Sedang', 'asset_category' => 'TIANG', 'network_type' => 'JTM', 'description' => 'Tiang sudut deviasi sedang (15-30 derajat)'],
                    ['code' => 'TM-4', 'name' => 'TM-4 Tiang Sudut Besar', 'asset_category' => 'TIANG', 'network_type' => 'JTM', 'description' => 'Tiang sudut deviasi besar (30-60 derajat)'],
                    ['code' => 'TM-5', 'name' => 'TM-5 Tiang Tarik / Sudut', 'asset_category' => 'TIANG', 'network_type' => 'JTM', 'description' => 'Tiang tarik ganda / sudut tajam (60-90 derajat)'],
                    ['code' => 'TM-6', 'name' => 'TM-6 Tiang Penegang', 'asset_category' => 'TIANG', 'network_type' => 'JTM', 'description' => 'Tiang penegang seksi lurus'],
                    ['code' => 'TM-7', 'name' => 'TM-7 Tiang Penegang Sudut', 'asset_category' => 'TIANG', 'network_type' => 'JTM', 'description' => 'Tiang penegang sudut'],
                    ['code' => 'TM-8', 'name' => 'TM-8 Gardu Tiang Portal', 'asset_category' => 'GARDU', 'network_type' => 'JTM', 'description' => 'Gardu trafo portal 2 tiang'],
                    ['code' => 'TM-9', 'name' => 'TM-9 Gardu Tiang Cantol', 'asset_category' => 'GARDU', 'network_type' => 'JTM', 'description' => 'Gardu trafo cantol 1 tiang'],
                    ['code' => 'TM-10', 'name' => 'TM-10 Tiang Akhir', 'asset_category' => 'TIANG', 'network_type' => 'JTM', 'description' => 'Tiang ujung / terminasi akhir penyulang'],
                    ['code' => 'TM-11', 'name' => 'TM-11 Tiang Percabangan', 'asset_category' => 'TIANG', 'network_type' => 'JTM', 'description' => 'Tiang percabangan 3 arah (T-Off)'],
                    ['code' => 'LBS', 'name' => 'Load Break Switch', 'asset_category' => 'SWITCH', 'network_type' => 'JTM', 'description' => 'Saklar pemutus beban motorized 20kV'],
                    ['code' => 'LBSM', 'name' => 'LBS Manual / PMS', 'asset_category' => 'SWITCH', 'network_type' => 'JTM', 'description' => 'Saklar pemutus beban manual / pemisah seksi'],
                    ['code' => 'PMCB_REC', 'name' => 'PMCB / Recloser', 'asset_category' => 'SWITCH', 'network_type' => 'JTM', 'description' => 'Recloser pemutus balik otomatis'],
                    ['code' => 'GI', 'name' => 'Gardu Induk', 'asset_category' => 'GARDU', 'network_type' => 'JTM', 'description' => 'Titik pasok hulu 20kV'],
                    ['code' => 'GH', 'name' => 'Gardu Hubung', 'asset_category' => 'GARDU', 'network_type' => 'JTM', 'description' => 'Pusat manuver distribusi 20kV'],
                    ['code' => 'DISTRIBUSI', 'name' => 'Trafo Distribusi', 'asset_category' => 'TRAFO', 'network_type' => 'JTM', 'description' => 'Trafo distribusi 20kV ke 380V/220V'],
                ];
                $db->table('construction_types')->insertBatch($constructions);
            }
        }
    }

    public function down()
    {
        // Safe rollback
    }
}
